version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_passwd
      - POSTGRES_DB=olgram
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-db:/bitnami/redis/data
    ports:
      - '6379:6379'

volumes:
  database:
  redis-db:
